version: 2.1

jobs:
  build-push-update-sync:
    docker:
      - image: jimdo/aws-python
    steps:
      - checkout
      # # Build Docker image
      - setup_remote_docker:
          version: 
          docker_layer_caching: true
      - run:
          name: build docker image
          command: |
            export AWS_ACCESS_KEY_ID=$username
            export AWS_SECRET_ACCESS_KEY=$password
            export AWS_DEFAULT_REGION=ap-south-1
            docker build -t auth-go-beta:$CIRCLE_BUILD_NUM .
            docker images
            apt-get update
            apt-get install -y awscli

            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 848634117349.dkr.ecr.ap-south-1.amazonaws.com
            docker tag auth-go-beta:$CIRCLE_BUILD_NUM 848634117349.dkr.ecr.ap-south-1.amazonaws.com/auth-go-beta:$CIRCLE_BUILD_NUM
            docker push ashiqummathoor/test1000:$CIRCLE_BUILD_NUM

      #       docker build -t ashiq .

      # # Optionally, you can push the image to a Docker registry
      # - run:
      #     name: Push Docker image
      #     command: |
      #       echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #       docker push your_image_name:latest

workflows:
  version: 2.1
  build:
    jobs:
      - build-push-update-sync
