version: 2.1

jobs:
  build-and-push:
    docker:
      - image: docker:latest

    steps:
      - checkout

      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            apk add --no-cache py-pip
            pip install awscli

      # Configure AWS CLI with ECR credentials
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set region ap-south-1 --profile swz-test
            aws configure set output json --profile swz-test
            aws configure set aws_access_key_id $username --profile swz-test
            aws configure set aws_secret_access_key $password --profile swz-test
            export AWS_DEFAULT_PROFILE=swz-test

      # Build and tag Docker image
      - run:
          name: Build and Tag Docker Image
          command: |
            docker build -t ashiq .
            # docker tag $AWS_ECR_REPO_URL:$CIRCLE_SHA1 $AWS_ECR_REPO_URL:latest

      # Login to AWS ECR
      - run:
          name: Login to AWS ECR
          command: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 848634117349.dkr.ecr.ap-south-1.amazonaws.com

      # Push Docker image to AWS ECR
      # - run:
      #     name: Push Docker Image to ECR
      #     command: |
      #       docker push $AWS_ECR_REPO_URL:$CIRCLE_SHA1
      #       docker push $AWS_ECR_REPO_URL:latest

workflows:
  version: 2.1
  build:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - test
