version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.7

    steps:
      - checkout

      # Install Docker client
      - run:
          name: Install Docker client
          command: |
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t ashiq .

      # # Optionally, you can push the image to a Docker registry
      # - run:
      #     name: Push Docker image
      #     command: |
      #       echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #       docker push your_image_name:latest

workflows:
  version: 2.1
  build:
    jobs:
      - build
