version: 2.1

jobs:
  build-push-update-sync:
    docker:
      - image: docker:20.10.14
    steps:
      - checkout
      # # Build Docker image
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: build docker image
          command: |
            docker build -t ashiqummathoor/test1000:$CIRCLE_BUILD_NUM .
            docker images
            echo "docker@0786" | docker login -u ashiqummathoor --password-stdin
            docker push ashiqummathoor/test1000:$CIRCLE_BUILD_NUM

      #       docker build -t ashiq .

      # # Optionally, you can push the image to a Docker registry
      # - run:
      #     name: Push Docker image
      #     command: |
      #       echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #       docker push your_image_name:latest

workflows:
  version: 2.1
  build:
    jobs:
      - build-push-update-sync
