version: 2.1

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      # Build Docker image
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
            docker build -t ashiq .

      # # Optionally, you can push the image to a Docker registry
      # - run:
      #     name: Push Docker image
      #     command: |
      #       echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #       docker push your_image_name:latest

workflows:
  version: 2.1
  build:
    jobs:
      - build
